apiVersion: apps/v1
kind: Deployment
metadata:
  name: callorder
  labels:
    app: callorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: callorder
  template:
    metadata:
      labels:
        app: callorder
    spec:
      containers:
        - name: callorder
          image: 651396752652.dkr.ecr.ap-northeast-2.amazonaws.com/callorder:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5